include: package:flutter_lints/flutter.yaml

analyzer:
    plugins:
        - custom_lint
    exclude:
        - lib/**.g.dart
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
