name: download_manager
description: A simple download manager for Android.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider:
  path:
  permission_handler:
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  flutter_downloader:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  arb_generator:
  app_store_screenshots:
    git:
      url: https://github.com/defuncart/app_store_screenshots
  flutter_launcher_icons:
  riverpod_generator: ^3.0.0-dev.11 
  custom_lint:
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  android: true
  image_path_android: "assets_dev/app_icons/app_icon.png"
  adaptive_icon_background: "#69F0AE"
  adaptive_icon_foreground: "assets_dev/app_icons/android_icon_foreground.png"
